### ISSUE TITLE
Problem with tweets ending with a number

### ISSUE THREAD

**Issue by Korko** [idevelop/longest-poem-in-the-world#4]
Hi,

Seems like the pronunciation dictionary doesn't handle numbers.
Example from the the app:
“i want to stan more groups now where do i start”
“i love brendon so much i can’t believe he’s 31”
“I guess im done.”
“I’m a sensitive bitch for sure tho .”

See the "31" trying to match "done".

Korko

**Comment by idevelop** [comment]
@Korko admittedly I haven't tested this in a while, but afaict, this function should be responsible for what you're requesting:

https://github.com/idevelop/longest-poem-in-the-world/blob/master/cloud/functions/fetch-tweets/index.js#L164

Looking at your example, is there any chance you selected them off-by-one, and "31" rhymes with "done"?

**Comment by idevelop** [comment]
Oh sorry, misread your comment. Are you saying "31" isn't supposed to rhyme with "done"? I'm not a native speaker but it sounds like a reasonable rhyme to me :)

**Comment by Korko** [comment]
I'm not a native one either but it appears you are right.
https://dictionary.cambridge.org/dictionary/english/done says it's /dʌn/
https://dictionary.cambridge.org/dictionary/english/one says it's /wʌn/

Not sure why but even when hearing by native, for me it doesn't rhyme but it's only me I suppose.

Sorry for the ticket :)

Thanks

**Comment by idevelop** [comment]
No worries @Korko, thanks for taking the time to report it!
